#!/usr/bin/env python3
"""Rebuild models/*.json from Higgsfield's per-model agent prompts (llms.txt).

Usage: python tools/sync_models.py [--from-dir DIR] [endpoint ...]

Without endpoints it discovers every model variant linked from the public
catalog at open.higgsfield.ai. Existing hand-written `pricing` rules are kept.
"""
import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "models"
UA = "Mozilla/5.0 (compatible; higgsfield-skill-sync/1.0)"
CATALOG = "https://open.higgsfield.ai"
LLMS = "https://dash.higgsfield.ai/models/{}/llms.txt"


def get(url):
    with urlopen(Request(url, headers={"User-Agent": UA}), timeout=60) as r:
        return r.read().decode("utf-8")


def discover():
    explore = get(f"{CATALOG}/explore")
    cards = set(re.findall(r'/models/([a-z0-9][a-z0-9./-]*?)/playground', explore))
    found = set(cards)
    for card in sorted(cards):
        page = get(f"{CATALOG}/models/{card}/playground")
        found.update(re.findall(r'/models/([a-z0-9][a-z0-9./-]*?)/(?:playground|api-reference)', page))
    return sorted(e for e in found if not e.startswith("workflows/"))


def slug(endpoint):
    return endpoint.replace("/", "-")


def section(text, heading):
    m = re.search(rf"^#+ {re.escape(heading)}\s*\n(.*?)(?=^#+ |\Z)", text, re.S | re.M)
    return m.group(1).strip() if m else ""


def json_block(text, heading):
    # The fenced block may follow a line or two of prose under the heading.
    lines = text.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if re.fullmatch(rf"#+ {re.escape(heading)}\s*", line))
    except StopIteration:
        return None
    for i in range(start + 1, len(lines)):
        if lines[i].startswith("#"):
            return None
        if lines[i].strip() == "```json":
            end = next(j for j in range(i + 1, len(lines)) if lines[j].strip() == "```")
            return json.loads("\n".join(lines[i + 1:end]))
    return None


def output_fields(text):
    schema = json_block(text, "Output Schema") or {}
    fields = []
    for option in schema.get("oneOf", []):
        if option.get("title") == "CompletedRequestStatus":
            fields = [k for k in option.get("properties", {}) if k not in ("request_id", "status", "status_url", "cancel_url")]
    return fields


def build(endpoint, text):
    title = re.search(r"^# (.+)$", text, re.M)
    summary = re.search(r"^> (.+(?:\n(?!\n).+)*)", text, re.M)
    category = re.search(r"\*\*Category\*\*: ([^\n]+)", text)
    schema = json_block(text, "Input JSON Schema")
    if not schema:
        raise ValueError("no input schema")
    pricing = section(text, "Pricing")
    spec = {
        "id": slug(endpoint),
        "name": title.group(1).strip() if title else endpoint,
        "endpoint": endpoint,
        "category": category.group(1).strip().rstrip(",") if category else "",
        "summary": re.sub(r"\s+", " ", summary.group(1)).strip() if summary else "",
        "docs": f"{CATALOG}/models/{endpoint}/api-reference",
        "agent_prompt": LLMS.format(endpoint),
        "checked": date.today().isoformat(),
        "pricing_note": "" if "not available" in pricing else re.sub(r"\s+", " ", pricing),
        "outputs": output_fields(text),
        "example": json_block(text, "Required Parameters Example") or {},
        "input_schema": schema,
    }
    old = MODELS / f"{spec['id']}.json"
    if old.exists():
        previous = json.loads(old.read_text(encoding="utf-8"))
        for key in ("pricing", "price_check", "sample_usd"):
            if key in previous:
                spec[key] = previous[key]
    return spec


PRICE_LABEL = {"api": "Exact USD from Higgsfield", "rule": "Computed from live rate",
               "unpriced": "Not given by API (needs --allow-unpriced)", "estimate-error": "Higgsfield estimate errors",
               "no-inputs": "No published inputs (console only)"}
GROUPS = [("Video", ("text2video", "image2video", "video2video")), ("Image", ("text2image", "image_edit")),
          ("Other", ("character",))]


def write_catalog():
    specs = [json.loads(p.read_text(encoding="utf-8")) for p in sorted(MODELS.glob("*.json"))]
    out = ["# Models", "",
           f"{len(specs)} Higgsfield API endpoints, generated by `tools/sync_models.py` from each model's agent prompt.",
           "Example prices are what `estimate` returned for the model's default settings on the check date; your "
           "settings and account discounts change them. Run `hf.py info <model>` for every parameter.", ""]
    for title, cats in GROUPS:
        rows = [s for s in specs if s.get("category", "").split(",")[0].strip() in cats]
        if not rows:
            continue
        out += [f"## {title}", "", "| Model | Name | Type | Price check | Example |", "|---|---|---|---|---|"]
        for s in rows:
            example = f"${s['sample_usd']}" if s.get("sample_usd") else ""
            out.append(f"| `{s['id']}` | {s.get('name', '')} | {s.get('category', '')} | "
                       f"{PRICE_LABEL.get(s.get('price_check'), 'Unchecked')} | {example} |")
        out.append("")
    (ROOT / "MODELS.md").write_text("\n".join(out), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("endpoints", nargs="*")
    ap.add_argument("--from-dir", help="read saved llms.txt files named <endpoint with / as _>.md instead of downloading")
    args = ap.parse_args()
    endpoints = args.endpoints or discover()
    MODELS.mkdir(exist_ok=True)
    ok, failed = 0, []
    for endpoint in endpoints:
        try:
            if args.from_dir:
                text = (Path(args.from_dir) / (endpoint.replace("/", "_") + ".md")).read_text(encoding="utf-8")
            else:
                text = get(LLMS.format(endpoint))
            spec = build(endpoint, text)
        except Exception as exc:  # keep going; report at the end
            failed.append(f"{endpoint}: {exc}")
            continue
        (MODELS / f"{spec['id']}.json").write_text(json.dumps(spec, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        ok += 1
    write_catalog()
    print(f"wrote {ok} model files and MODELS.md")
    for line in failed:
        print("FAILED", line, file=sys.stderr)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
